### ISSUE TITLE
Cant get what is that and how to use

### ISSUE THREAD

**Issue by orihomie** [codecept-js/configure#1]
Hi, can you please provide more detailed info on this module? I

**Comment by DavertMik** [comment]
I tried all my best :sleepy: . Could you help me by asking some questions?

Basically this is a collection of common configuration patterns that can be used in config. 
For instance, `setHeadless` enables headless mode for any helper which is enabled. 
Most of helpers just require adding `show: true` while WebDriver + headless chrome requires updating capabilities. This config hook can set headless mode for both cases

**Comment by DavertMik** [comment]
I tried to answer everything here https://www.youtube.com/watch?v=onBnfo_rJa4
